name: Say Hello 2

on:
  push:
    branches: 
      - main

jobs:
  hello_world2:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola"

      - name: Echo 2 
        run: | 
          echo "Echo 2 "
